/**
 * Writes src/shared/build.ts (gitignored) before every compile: `bun scripts/build-info.ts [--channel dev|prod] [--dirty]`
 *
 * Same content `typetorch build` writes, so the template compiles without the CLI. It is the only file that uses the
 * `$git()` / `$compileTime()` macros, and it is rewritten every build, so rbxtsc always recompiles it and the git
 * info can't go stale. `$git()` has no dirty flag: without `--dirty` it comes from `git status --porcelain`.
 *
 * The last line is a timestamp comment: rbxtsc builds incrementally and skips a file whose text did not change, which
 * would keep a stale `$git()` / `$compileTime()` (e.g. a new commit with the same channel and dirty flag).
 *
 * Set TYPETORCH_SKIP_BUILD_INFO=1 to keep a build.ts the CLI already wrote (the CLI then runs `bun run build`).
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dir, "..");

if (process.env.TYPETORCH_SKIP_BUILD_INFO === "1") {
	console.log("build-info: kept the existing src/shared/build.ts");
	process.exit(0);
}

function arg(name: string): string | undefined {
	const index = Bun.argv.indexOf(name);
	if (index !== -1) return Bun.argv[index + 1];
	return Bun.argv.find((value) => value.startsWith(`${name}=`))?.slice(name.length + 1);
}

const channel = arg("--channel") ?? process.env.TYPETORCH_CHANNEL ?? "dev";
if (channel !== "dev" && channel !== "prod") throw new Error(`--channel must be dev or prod, got ${channel}`);

let dirty: boolean;
if (Bun.argv.includes("--dirty")) {
	dirty = arg("--dirty") !== "false";
} else {
	const status = Bun.spawnSync(["git", "status", "--porcelain"], { cwd: root, stdout: "pipe", stderr: "pipe" });
	dirty = status.exitCode === 0 && status.stdout.toString().trim().length > 0;
}

const content = [
	"// Generated by `typetorch build`. Do not edit.",
	'import { $compileTime, $git } from "rbxts-transform-debug";',
	'import type { BuildInfo } from "@typetorch/framework";',
	'const GIT = $git("Branch", "Commit");',
	`export const BUILD: BuildInfo = { branch: GIT.Branch, commit: GIT.Commit, dirty: ${dirty}, channel: "${channel}", builtAt: $compileTime() };`,
	`// ${new Date().toISOString()}`,
	"",
].join("\n");

writeFileSync(join(root, "src", "shared", "build.ts"), content);
console.log(`build-info: channel ${channel}${dirty ? ", dirty" : ""}`);
